//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CateringAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class food_category_discount
    {
        public int id { get; set; }
        public int food_category_id { get; set; }
        public double discount_percent { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime valid_from { get; set; }
        public System.DateTime valid_until { get; set; }
    
        public virtual food_category food_category { get; set; }
    }
}
