//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CateringAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public food()
        {
            this.combo_menu_item = new HashSet<combo_menu_item>();
            this.order_food_item = new HashSet<order_food_item>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string unit_of_measurement { get; set; }
        public int food_category_id { get; set; }
        public bool is_visible { get; set; }
        public string ingredients { get; set; }
        public double price { get; set; }
        public double discount_percent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<combo_menu_item> combo_menu_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_food_item> order_food_item { get; set; }
        public virtual food_category food_category { get; set; }
    }
}
