//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CateringAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_food_item
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> food_id { get; set; }
        public double price { get; set; }
        public int amount { get; set; }
    
        public virtual food food { get; set; }
        public virtual order order { get; set; }
    }
}
