//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CateringAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.order_combo_item = new HashSet<order_combo_item>();
            this.order_food_item = new HashSet<order_food_item>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_completed { get; set; }
        public string delivery_location { get; set; }
        public double price { get; set; }
        public Nullable<double> price_with_discount { get; set; }
        public Nullable<bool> is_complete { get; set; }
        public int payment_method_id { get; set; }
        public int discount_id { get; set; }
        public int delivery_id { get; set; }
    
        public virtual delivery_method delivery_method { get; set; }
        public virtual order_discount order_discount { get; set; }
        public virtual payment_method payment_method { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_combo_item> order_combo_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_food_item> order_food_item { get; set; }
    }
}
